#Campbell Boswell & Scott Westvold
#AIM - Automated Investment Manager
#cs701 - Senior Project
#constituents_filter_except.py

'''
    A dictionary with a series of first words from the names of companies on the
    S&P 500. The value pairs are the subsequent words in the company names. This
    dictionary is used during the filtering process.   
'''

filter_dict = {
    'advance': ['auto'],
    'advanced': ['micro'],
    'affiliated': ['managers'],
    'air': ['products'],
    'alaska': ['air'],
    'align': ['technology'],
    'alliance': ['data'],
    'alliant': ['energy'],
    'american': ['airlines', 'electric', 'express', 'tower', 'water'],
    'anthem': ['inc'],
    'apartment': ['investment'],
    'applied': ['materials'],
    'automatic': ['data'],
    'best': ['buy'],
    'booking': ['holdings'],
    'boston': ['properties', 'scientific'],
    'campbell': ['soup'],
    'capital': ['one'],
    'carnival': ['corp'],
    'charles': ['schwab'],
    'charter': ['communications'],
    'citizens': ['financial'],
    'consolidated': ['edison'],
    'constellation': ['brands'],
    'crown': ['castle'],
    'digital': ['realty'],
    'discover': ['financial'],
    'dish': ['network'],
    'dollar': ['general', 'tree'],
    'dr': ['pepper'],
    'duke': ['energy', 'realty'],
    'edwards': ['lifesciences'],
    'electronic': ['arts'],
    'emerson': ['electric'],
    'equity': ['residential'],
    'express': ['scripts'],
    'extra': ['space'],
    'federal': ['realty'],
    'fifth': ['third'],
    'foot': ['locker'],
    'fortune': ['brands'],
    'general': ['dynamics', 'electric', 'growth', 'mills', 'motors'],
    'genuine': ['parts'],
    'global': ['payments'],
    'harris': ['corporation'],
    'hartford': ['financial'],
    'henry': ['schein'],
    'home': ['depot'],
    'huntington': ['bancshares', 'ingalls'],
    'illinois': ['tool'],
    'intercontinental': ['exchange'],
    'international': ['business', 'paper'],
    'intuitive': ['surgical'],
    'iron': ['mountain'],
    'johnson': ['johnson', 'controls'],
    'laboratory': ['corp'],
    'lincoln': ['national'],
    'marathon': ['oil', 'petroleum'],
    'marsh': ['mclennan'],
    'martin': ['marietta'],
    'michael': ['kors'],
    'mohawk': ['industries'],
    'monster': ['beverage'],
    'morgan': ['stanley'],
    'national': ['oilwell'],
    'noble': ['energy'],
    'norfolk': ['southern'],
    'northern': ['trust'],
    'norwegian': ['cruise'],
    'o': ['reilly'],
    'occidental': ['petroleum'],
    'packaging': ['corporation'],
    'philip': ['morris'],
    'pinnacle': ['west'],
    'pioneer': ['natural'],
    'polo': ['ralph'],
    'principal': ['financial'],
    'procter': ['gamble'],
    'progressive': ['corp'],
    'public': ['storage'],
    'quest': ['diagnostics'],
    'range': ['resources'],
    'raymond': ['james'],
    'red': ['hat'],
    'regions': ['financial'],
    'republic': ['services'],
    'robert': ['half'],
    'rockwell': ['automation', 'collins'],
    'ross': ['stores'],
    'royal': ['caribbean'],
    'sealed': ['air'],
    'sherwin': ['williams'],
    'simon': ['property'],
    'sl': ['green'],
    'snap': ['on'],
    'southern': ['co'],
    'southwest': ['airlines'],
    'stanley': ['black'],
    'state': ['street'],
    'take': ['two'],
    'te': ['connectivity'],
    'texas': ['instruments'],
    'the': ['bank', 'clorox', 'cooper', 'hershey', 'mosaic', 'travelers', 'walt'],
    'tiffany': ['co'],
    'time': ['warner'],
    'total': ['system'],
    'tractor': ['supply'],
    'twenty': ['first'],
    'tyson': ['foods'],
    'under': ['armour'],
    'union': ['pacific'],
    'united': ['continental', 'health', 'parcel', 'rentals', 'technologies'],
    'universal': ['health'],
    'waste': ['management'],
    'waters': ['corporation'],
    'western': ['digital'],
    'williams': ['cos'],
    'willis': ['towers'],
    'yum': ['brands']
}
